import { useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { Link, useLocation, useParams } from 'wouter';
import { toast } from 'sonner';
import { Activity, Award, ArrowRight, ArrowUpRight, BriefcaseBusiness, Check, ChevronRight, CircleAlert, Clock3, Download, GraduationCap, Plus, Search, Sparkles, Target, Users, X } from 'lucide-react';
import { signInWithPassword, signUpWithPassword, useDemoMode, isSupabaseConfigured, getDataMode, signOut } from '@/lib/data';
import { saveEmployee, deleteEmployee, saveSkill, saveCertification, saveCourse, updateEnrollment, enrollEmployee, updateEmployeeSkill, resolveGap, saveSettings } from '@/lib/data';
import type { AppSettings, CertificationInput, CourseInput, EmployeeInput, SkillInput, SkillLevel } from '@/lib/types';
import { useWorkspace } from '@/lib/use-workspace';

type AnyRow = Record<string, any>;
const arr = (d: AnyRow | null, ...keys: string[]): AnyRow[] => { for (const k of keys) if (Array.isArray(d?.[k])) return d[k]; return []; };
const nameOf = (e: AnyRow) => e.fullName || e.name || 'Unnamed';
const initials = (s: string) => s.split(/\s+/).map(x => x[0]).join('').slice(0,2).toUpperCase() || '—';
const dateText = (value?: string) => value ? new Date(value).toLocaleDateString('en', { month:'short', day:'numeric', year:'numeric' }) : '—';
const pct = (n: any) => `${Math.round(Number(n)||0)}%`;
const levelPercent = (level:any) => typeof level==='number' ? level*20 : ({Beginner:20,Basic:35,Intermediate:60,Advanced:80,Expert:100} as Record<string,number>)[String(level)]||0;

function PageTitle({ eyebrow, title, subtitle, action }: { eyebrow: string; title: string; subtitle: string; action?: ReactNode }) {
 return <div className="mb-7 flex flex-wrap items-end justify-between gap-4 animate-rise"><div><div className="mb-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#568878]">{eyebrow}</div><h1 className="font-[Manrope] text-[29px] font-extrabold leading-tight tracking-[-.045em] text-[#20373d] md:text-[34px]">{title}</h1><p className="mt-2 max-w-2xl text-[13px] leading-6 text-[#72807d]">{subtitle}</p></div>{action}</div>;
}
function Button({ children, onClick, secondary=false, testId }: { children: ReactNode; onClick?:()=>void; secondary?:boolean; testId?:string }) {
 return <button data-testid={testId} onClick={onClick} className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-[10px] text-[12px] font-bold transition hover:-translate-y-px ${secondary?'border border-[#ded9ce] bg-white text-[#526461] hover:bg-[#f8f6f0]':'bg-[#276b58] text-white shadow-[0_5px_12px_rgba(39,107,88,.15)] hover:bg-[#1d5c4b]'}`}>{children}</button>;
}
function Panel({ children, className='' }: {children:ReactNode;className?:string}) { return <section className={`rounded-2xl border border-[#e6e1d7] bg-white ${className}`}>{children}</section>; }
function Empty({ label, onAdd }: {label:string;onAdd?:()=>void}) { return <div className="grid min-h-[230px] place-items-center p-7 text-center"><div><div className="mx-auto mb-3 grid h-11 w-11 place-items-center rounded-2xl bg-[#eef4ef] text-[#43826d]"><Sparkles size={19}/></div><div className="text-sm font-bold text-[#34494b]">A clear slate</div><p className="mt-1 max-w-xs text-xs leading-5 text-[#7a8783]">{label}</p>{onAdd&&<button onClick={onAdd} className="mt-4 text-xs font-bold text-[#367962]">Add the first record</button>}</div></div>; }
function TableEmpty({ colSpan, text }: {colSpan:number;text:string}) { return <tr><td colSpan={colSpan} className="py-16 text-center text-sm text-[#7a8783]">{text}</td></tr>; }

function RecordDialog({ kind, initial, close, data, refresh }: {kind:string;initial?:AnyRow;close:()=>void;data:AnyRow|null;refresh:()=>void}) {
 const [busy,setBusy]=useState(false);
 const [form,setForm]=useState<AnyRow>(initial||{});
 const update=(key:string,value:any)=>setForm((prev:AnyRow)=>({...prev,[key]:value}));
 const field=(key:string,label:string,placeholder='')=><label className="block text-[11px] font-bold text-[#52635f]">{label}<input data-testid={`input-${key}`} value={form[key]??''} onChange={e=>update(key,e.target.value)} placeholder={placeholder} className="mt-1.5 w-full rounded-xl border border-[#e3dfd5] bg-[#fbfaf6] px-3 py-2.5 text-[13px] font-normal text-[#263b40] outline-none focus:border-[#79a995] focus:ring-2 focus:ring-[#dcece3]"/></label>;
 const select=(key:string,label:string,options:string[]) => <label className="block text-[11px] font-bold text-[#52635f]">{label}<select data-testid={`select-${key}`} value={form[key]??''} onChange={e=>update(key,e.target.value)} className="mt-1.5 w-full rounded-xl border border-[#e3dfd5] bg-[#fbfaf6] px-3 py-2.5 text-[13px] font-normal text-[#263b40] outline-none focus:border-[#79a995]"><option value="">Select…</option>{options.map(x=><option key={x}>{x}</option>)}</select></label>;
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{
   if(kind==='employee') await saveEmployee({...form,status:form.status||'Active'} as EmployeeInput); else if(kind==='skill') await saveSkill({...form,description:form.description||''} as SkillInput); else if(kind==='certification') await saveCertification(form as CertificationInput); else if(kind==='course') {const {requiredSkillsText,...courseForm}=form;await saveCourse({...courseForm,requiredSkills:typeof requiredSkillsText==='string'?requiredSkillsText.split(',').map((x:string)=>x.trim()).filter(Boolean):form.requiredSkills||[]} as CourseInput);} else if(kind==='settings') await saveSettings(form as AppSettings);
   toast.success(`${kind[0].toUpperCase()+kind.slice(1)} saved`); await refresh(); close();
 }catch(err){toast.error(err instanceof Error?err.message:'Could not save changes.');}finally{setBusy(false);}};
 const title=`${initial?'Edit':'Add'} ${kind}`;
 return <div className="fixed inset-0 z-50 grid place-items-center bg-[#10262e]/45 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><form onSubmit={submit} className="max-h-[90dvh] w-full max-w-[520px] overflow-y-auto rounded-2xl bg-[#fcfbf6] p-6 shadow-2xl">
   <div className="mb-5 flex items-start justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[.17em] text-[#568878]">Workspace record</div><h2 className="mt-1 font-[Manrope] text-xl font-extrabold text-[#233a40]">{title}</h2></div><button type="button" onClick={close} className="rounded-lg p-2 text-[#74827e]" aria-label="Close"><X size={18}/></button></div>
   <div className="grid gap-3 sm:grid-cols-2">
    {kind==='employee'&&<>{field('fullName','Full name','e.g. Sam Rivera')}{field('employeeId','Employee ID','ST-014')}{field('email','Work email','name@company.com')}{field('phone','Phone number')}{field('department','Department','Product')}{field('jobRole','Job role','Senior analyst')}{field('manager','Manager')}{field('location','Location')}{select('status','Status',['Active','On leave','Inactive'])}{field('joiningDate','Joining date','YYYY-MM-DD')}</>}
    {kind==='skill'&&<>{field('name','Skill name')}{select('category','Category',['Technical','Soft Skill','Leadership','Domain','Tools','Management'])}<label className="col-span-full block text-[11px] font-bold text-[#52635f]">Description<textarea value={form.description??''} onChange={e=>update('description',e.target.value)} rows={3} className="mt-1.5 w-full rounded-xl border border-[#e3dfd5] bg-[#fbfaf6] p-3 text-[13px] font-normal outline-none"/></label></>}
    {kind==='certification'&&<>{field('name','Certification name')}{field('provider','Issuing provider')}{field('employeeId','Employee ID')}{field('issueDate','Issue date','YYYY-MM-DD')}{field('expiryDate','Expiry date','YYYY-MM-DD')}</>}
    {kind==='course'&&<>{field('name','Course title')}{field('instructor','Instructor')}{field('duration','Duration')}{select('category','Category',['Technical','Soft Skill','Leadership','Domain','Tools','Management'])}{field('requiredSkillsText','Required skills (comma separated)')}{labelDescription()}</>}
    {kind==='settings'&&<>{field('organizationName','Organization name')}{field('displayName','Your name')}{field('email','Email')}</>}
   </div>
   <div className="mt-6 flex justify-end gap-2"><Button secondary onClick={close}>Cancel</Button><button disabled={busy} className="rounded-xl bg-[#276b58] px-5 py-2.5 text-xs font-bold text-white disabled:opacity-60">{busy?'Saving…':'Save changes'}</button></div>
 </form></div>;
 function labelDescription(){return <label className="col-span-full block text-[11px] font-bold text-[#52635f]">Description<textarea value={form.description??''} onChange={e=>update('description',e.target.value)} rows={3} className="mt-1.5 w-full rounded-xl border border-[#e3dfd5] bg-[#fbfaf6] p-3 text-[13px] font-normal outline-none"/></label>}
}

function Dashboard({data,loading,error,refresh}:{data:AnyRow|null;loading:boolean;error:string;refresh:()=>void}) {
 const people=arr(data,'employees','people'), skills=arr(data,'skills'), certs=arr(data,'certifications'), courses=arr(data,'courses'), gaps=arr(data,'skillGaps','skillGapsData','gaps'), activities=arr(data,'activities');
 const active=people.filter(e=>(e.status||'Active').toLowerCase()==='active').length;
 const expiring=certs.filter(c=>{const days=(new Date(c.expiryDate||0).getTime()-Date.now())/86400000;return days>=0&&days<60;}).length;
 if(loading)return <LoadingPage/>;
 if(error)return <ErrorPanel error={error} retry={refresh}/>;
 return <><PageTitle eyebrow={`${new Date().toLocaleDateString('en',{weekday:'long',month:'long',day:'numeric'})} · your workspace`} title="People & skills, in focus." subtitle="A clear view of the capabilities your teams have today — and where to invest next." action={<Link href="/employees" className="inline-flex items-center gap-2 rounded-xl bg-[#276b58] px-4 py-[10px] text-[12px] font-bold text-white no-underline shadow-[0_5px_12px_rgba(39,107,88,.15)]"><Plus size={15}/>Manage people</Link>}/>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
   <Metric label="Active people" value={active} note={`${people.length} total profiles`} icon={Users} tone="green"/>
   <Metric label="Skills in library" value={skills.length} note="Across all categories" icon={BriefcaseBusiness} tone="blue"/>
   <Metric label="Certifications at risk" value={expiring} note="Expiring in next 60 days" icon={Award} tone="amber"/>
   <Metric label="Open skill gaps" value={gaps.filter(g=>!g.resolved).length} note="Prioritized development needs" icon={Target} tone="rose"/>
  </div>
  <div className="mt-5 grid gap-4 xl:grid-cols-[1.55fr_1fr]">
   <Panel className="p-5 md:p-6"><div className="mb-5 flex items-start justify-between"><div><h2 className="font-[Manrope] text-base font-extrabold text-[#273e43]">Capability snapshot</h2><p className="mt-1 text-xs text-[#7b8782]">A live read on learning across the organization</p></div><span className="rounded-lg bg-[#eef5f0] px-2.5 py-1.5 text-[10px] font-bold text-[#387660]">WORKFORCE</span></div>
    <div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-[#f7f5ef] p-4"><div className="text-[11px] font-semibold text-[#798580]">Course catalogue</div><div className="mt-2 flex items-end justify-between"><span className="font-[Manrope] text-3xl font-extrabold text-[#27434a]">{courses.length}</span><span className="text-[10px] text-[#81908a]">available courses</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[#e7e4db]"><div className="h-full rounded-full bg-[#65a88b]" style={{width:`${Math.min(100,courses.length*8)}%`}}/></div></div>
    <div className="rounded-xl bg-[#f7f5ef] p-4"><div className="text-[11px] font-semibold text-[#798580]">Team coverage</div><div className="mt-2 flex items-end justify-between"><span className="font-[Manrope] text-3xl font-extrabold text-[#27434a]">{people.length?Math.round((people.length-gaps.filter(g=>!g.resolved).length)/people.length*100):0}<small className="text-base">%</small></span><span className="text-[10px] text-[#81908a]">without open gaps</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[#e7e4db]"><div className="h-full rounded-full bg-[#dfad65]" style={{width:`${people.length?Math.max(8,100-gaps.filter(g=>!g.resolved).length/people.length*100):0}%`}}/></div></div></div>
    <div className="mt-4 flex items-center justify-between border-t border-[#eeeae2] pt-4"><div className="text-xs text-[#71807b]"><span className="font-bold text-[#334d4d]">{arr(data,'enrollments').length}</span> learning enrollments currently tracked</div><Link href="/analytics" className="flex items-center gap-1 text-xs font-bold text-[#367962] no-underline">Explore analytics <ArrowRight size={14}/></Link></div>
   </Panel>
   <Panel className="p-5 md:p-6"><div className="mb-5 flex items-start justify-between"><div><h2 className="font-[Manrope] text-base font-extrabold text-[#273e43]">Needs your attention</h2><p className="mt-1 text-xs text-[#7b8782]">Small actions, meaningful progress</p></div><CircleAlert size={17} className="text-[#d99554]"/></div>
    <div className="space-y-2.5"><AttentionRow color="amber" value={expiring} label="certifications nearing expiry" href="/certifications"/><AttentionRow color="rose" value={gaps.filter(g=>!g.resolved).length} label="priority skill gaps to review" href="/skill-gaps"/><AttentionRow color="green" value={arr(data,'enrollments').filter(e=>e.status==='in_progress'||e.status==='In progress').length} label="learners currently in progress" href="/training"/></div>
    <div className="mt-5 rounded-xl bg-[#f6f4ed] p-3.5"><div className="flex items-center gap-2 text-[11px] font-bold text-[#516360]"><Clock3 size={14}/>Upcoming reviews</div><p className="mt-1.5 text-[11px] leading-5 text-[#7b8782]">{activities.length ? `${activities.length} recent workspace updates to review.` : 'No upcoming review dates have been added yet.'}</p></div>
   </Panel>
  </div>
  <div className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_.9fr]">
   <Panel><div className="flex items-center justify-between border-b border-[#eeeae2] px-5 py-4"><div><h2 className="font-[Manrope] text-sm font-extrabold text-[#273e43]">Priority development</h2><p className="mt-1 text-[11px] text-[#7b8782]">Highest priority open gaps</p></div><Link href="/skill-gaps" className="text-xs font-bold text-[#367962] no-underline">View all</Link></div>
   {gaps.filter(g=>!g.resolved).slice(0,4).map((g,i)=><div key={g.id??i} className="flex items-center gap-3 border-b border-[#f1eee8] px-5 py-3 last:border-0"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#f9eee5] text-[#bd7444]"><Target size={16}/></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold text-[#344b4d]">{g.skillName||g.skill?.name||g.name||'Skill development'}</div><div className="mt-1 text-[10px] text-[#82908a]">{g.employeeName||g.fullName||'Team member'} · {g.priority||'Priority'} priority</div></div><ChevronRight size={15} className="text-[#a7b0aa]"/></div>)}
   {!loading&&gaps.filter(g=>!g.resolved).length===0&&<Empty label="No open skill gaps. Development planning is up to date."/>}</Panel>
   <Panel><div className="flex items-center justify-between border-b border-[#eeeae2] px-5 py-4"><div><h2 className="font-[Manrope] text-sm font-extrabold text-[#273e43]">Recent activity</h2><p className="mt-1 text-[11px] text-[#7b8782]">Across your people workspace</p></div><ActivityMark/></div>
   {activities.slice(0,4).map((a,i)=><div key={a.id??i} className="flex gap-3 border-b border-[#f1eee8] px-5 py-3 last:border-0"><div className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[#76ad92]"/><div><div className="text-xs leading-5 text-[#485b59]">{a.description||a.message||`${a.type||'Workspace'} updated`}</div><div className="mt-1 text-[10px] text-[#94a09b]">{dateText(a.createdAt||a.date||a.timestamp)}</div></div></div>)}
   {activities.length===0&&<Empty label="Updates will appear here as your team records learning activity."/>}</Panel>
  </div>
 </>;
}
function ActivityMark(){return <div className="grid h-8 w-8 place-items-center rounded-lg bg-[#edf5f0] text-[#4c8a72]"><Activity size={15}/></div>}
function Metric({label,value,note,icon:Icon,tone}:{label:string;value:any;note:string;icon:any;tone:string}) {
 const colors:Record<string,string>={green:'bg-[#eaf3ed] text-[#41816a]',blue:'bg-[#eaf1f3] text-[#54818e]',amber:'bg-[#faf0e2] text-[#c28442]',rose:'bg-[#f8ece9] text-[#ba6e61]'};
 return <Panel className="p-4"><div className="flex items-start justify-between"><div><div className="text-[11px] font-semibold text-[#77847f]">{label}</div><div data-testid={`metric-${label.toLowerCase().replaceAll(' ','-')}`} className="mt-2 font-[Manrope] text-[31px] font-extrabold leading-none tracking-[-.05em] text-[#284248]">{value}</div></div><div className={`grid h-9 w-9 place-items-center rounded-xl ${colors[tone]}`}><Icon size={17}/></div></div><div className="mt-3 text-[10px] text-[#8a9691]">{note}</div></Panel>;
}
function AttentionRow({color,value,label,href}:{color:string;value:any;label:string;href:string}){return <Link href={href} className="flex items-center gap-3 rounded-xl bg-[#f8f6f0] px-3.5 py-3 no-underline hover:bg-[#f1efe7]"><span className={`h-2 w-2 rounded-full ${color==='amber'?'bg-[#dc9a57]':color==='rose'?'bg-[#c87c70]':'bg-[#61a383]'}`}/><span className="font-[Manrope] text-sm font-extrabold text-[#344b4d]">{value}</span><span className="flex-1 text-[11px] text-[#71807b]">{label}</span><ChevronRight size={14} className="text-[#a6b0aa]"/></Link>}
function LoadingPage(){return <div className="animate-pulse"><div className="mb-8 h-8 w-64 rounded bg-[#e6e3da]"/><div className="grid gap-3 sm:grid-cols-4">{[0,1,2,3].map(x=><div key={x} className="h-28 rounded-2xl bg-[#eae7df]"/> )}</div><div className="mt-5 h-72 rounded-2xl bg-[#eae7df]"/></div>}
function ErrorPanel({error,retry}:{error:string;retry:()=>void}){return <div className="rounded-2xl border border-[#ead6cd] bg-[#fffaf6] p-8"><div className="font-[Manrope] font-bold text-[#884e3a]">Workspace data unavailable</div><p className="mt-2 text-sm text-[#7e6f68]">{error}</p><button onClick={retry} className="mt-4 rounded-lg bg-[#276b58] px-4 py-2 text-xs font-bold text-white">Retry</button></div>}

function Employees({data,refresh}:{data:AnyRow|null;refresh:()=>void}) {
 const people=arr(data,'employees','people'), [query,setQuery]=useState(''),[dept,setDept]=useState('All departments'),[status,setStatus]=useState('All statuses'),[dialog,setDialog]=useState(false),[selected,setSelected]=useState<AnyRow|undefined>();
 const departments=Array.from(new Set(people.map(e=>e.department).filter(Boolean)));
 const filtered=people.filter(e=>`${nameOf(e)} ${e.email||''} ${e.jobRole||''} ${e.department||''}`.toLowerCase().includes(query.toLowerCase())&&(dept==='All departments'||e.department===dept)&&(status==='All statuses'||(e.status||'Active')===status));
 const remove=async(row:AnyRow)=>{if(!window.confirm(`Remove ${nameOf(row)} from the directory?`))return;try{await deleteEmployee(row.id??row.employeeId);toast.success('Employee removed');await refresh();}catch(e){toast.error(e instanceof Error?e.message:'Could not delete employee.')}};
 return <><PageTitle eyebrow="People directory" title="Employees" subtitle="Find a person, understand their role, and keep their growth plan moving." action={<Button onClick={()=>setDialog(true)} testId="button-add-employee"><Plus size={15}/>Add employee</Button>}/>
 <Panel className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#eeeae2] p-4 md:flex-row md:items-center md:justify-between"><div className="relative flex-1 md:max-w-[380px]"><Search size={15} className="absolute left-3 top-3 text-[#8c9892]"/><input id="workspace-search" data-testid="input-search-employees" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, role, or email…" className="w-full rounded-xl border border-[#e5e0d5] bg-[#fbfaf6] py-2.5 pl-9 pr-3 text-xs outline-none focus:border-[#83ae9a]"/></div><div className="flex gap-2"><select data-testid="filter-department" value={dept} onChange={e=>setDept(e.target.value)} className="rounded-xl border border-[#e5e0d5] bg-white px-3 py-2 text-xs text-[#5d6d68]"><option>All departments</option>{departments.map((d:any)=><option key={d}>{d}</option>)}</select><select data-testid="filter-status" value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-[#e5e0d5] bg-white px-3 py-2 text-xs text-[#5d6d68]"><option>All statuses</option>{['Active','On leave','Inactive'].map(s=><option key={s}>{s}</option>)}</select></div></div>
 <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#faf9f5] text-[10px] uppercase tracking-[.12em] text-[#82908a]"><tr>{['Employee','Department / role','Manager','Location','Status',''].map((h,i)=><th key={i} className="px-5 py-3 font-bold">{h}</th>)}</tr></thead><tbody className="divide-y divide-[#f0ede6]">{filtered.map((e,i)=><tr key={e.id??e.employeeId??i} data-testid={`row-employee-${e.id??i}`} className="group hover:bg-[#fbfaf6]"><td className="px-5 py-3.5"><Link href={`/employees/${e.id??e.employeeId}`} className="flex items-center gap-3 no-underline"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#eaf1ec] text-[10px] font-bold text-[#3e7664]">{initials(nameOf(e))}</span><span><span className="block text-xs font-bold text-[#32484b]">{nameOf(e)}</span><span className="mt-0.5 block text-[10px] text-[#89948f]">{e.email||e.employeeId||'No email recorded'}</span></span></Link></td><td className="px-5 py-3.5"><div className="text-xs font-semibold text-[#52635f]">{e.department||'—'}</div><div className="mt-0.5 text-[10px] text-[#89948f]">{e.jobRole||'—'}</div></td><td className="px-5 py-3.5 text-xs text-[#667671]">{e.manager||'—'}</td><td className="px-5 py-3.5 text-xs text-[#667671]">{e.location||'—'}</td><td className="px-5 py-3.5"><StatusBadge value={e.status||'Active'}/></td><td className="px-4 py-3.5"><div className="flex items-center gap-2 opacity-0 transition group-hover:opacity-100"><button aria-label={`Edit ${nameOf(e)}`} onClick={()=>{setFormRecord(e);setDialog(true);}} className="text-xs font-bold text-[#43816b]">Edit</button><button aria-label={`Delete ${nameOf(e)}`} onClick={()=>void remove(e)} className="text-xs font-bold text-[#b86c5f]">Delete</button></div></td></tr>)}
 {filtered.length===0&&<TableEmpty colSpan={6} text={people.length?'No people match those filters. Try broadening your search.':'No employee records yet. Add the first person to get started.'}/>}</tbody></table></div><div className="flex items-center justify-between px-5 py-3 text-[10px] text-[#82908a]"><span>Showing {filtered.length} of {people.length} people</span><span className="mono">DIRECTORY · LIVE</span></div></Panel>
 {dialog&&<RecordDialog kind="employee" initial={selectedRecord} close={()=>{setDialog(false);setSelected(undefined);setFormRecord(undefined);}} data={data} refresh={refresh}/>}
 </>;
}
let selectedRecord:AnyRow|undefined;
function setFormRecord(row?:AnyRow){selectedRecord=row;}
function StatusBadge({value}:{value:string}) {const v=value.toLowerCase();const cls=v.includes('active')||v.includes('complete')||v.includes('valid')?'bg-[#e9f3ec] text-[#438069]':v.includes('progress')?'bg-[#edf2f5] text-[#557b8b]':v.includes('expir')||v.includes('due')?'bg-[#faf0e2] text-[#b87c3e]':'bg-[#f1eee7] text-[#777e77]';return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ${cls}`}>{value}</span>}

function Skills({data,refresh}:{data:AnyRow|null;refresh:()=>void}) {
 const skills=arr(data,'skills'), [q,setQ]=useState(''),[category,setCategory]=useState('All categories'),[dialog,setDialog]=useState(false);
 const categories=Array.from(new Set(skills.map(s=>s.category).filter(Boolean)));
 const filtered=skills.filter(s=>`${s.name} ${s.category||''} ${s.description||''}`.toLowerCase().includes(q.toLowerCase())&&(category==='All categories'||s.category===category));
 return <><PageTitle eyebrow="Capability framework" title="Skills library" subtitle="The shared language for what your people know — and what they are ready to learn." action={<Button onClick={()=>setDialog(true)} testId="button-add-skill"><Plus size={15}/>Add a skill</Button>}/>
 <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="relative w-full max-w-[380px]"><Search size={15} className="absolute left-3 top-3 text-[#8c9892]"/><input data-testid="input-search-skills" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search skills…" className="w-full rounded-xl border border-[#e5e0d5] bg-white py-2.5 pl-9 pr-3 text-xs outline-none focus:border-[#83ae9a]"/></div><select data-testid="filter-skill-category" value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-[#e5e0d5] bg-white px-3 py-2.5 text-xs text-[#5d6d68]"><option>All categories</option>{categories.map((c:any)=><option key={c}>{c}</option>)}</select></div>
 <div className="mb-4 flex flex-wrap gap-2">{categories.slice(0,5).map((c:any,i)=><span key={c} className={`rounded-full px-3 py-1.5 text-[10px] font-bold ${i===0?'bg-[#e8f1eb] text-[#3f7a65]':'bg-white text-[#74817b] border border-[#e9e4da]'}`}>{c} <span className="ml-1 opacity-60">{skills.filter(s=>s.category===c).length}</span></span>)}</div>
 <Panel className="overflow-hidden"><div className="grid grid-cols-1 divide-y divide-[#eeeae2] sm:grid-cols-2 sm:divide-x sm:divide-y">{filtered.map((s,i)=><article key={s.id??i} className="group p-5 transition hover:bg-[#fbfaf6]"><div className="flex items-start justify-between gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf4ef] text-[#4b886f]"><BriefcaseBusiness size={18}/></div><span className="rounded-full bg-[#f2f0e9] px-2.5 py-1 text-[9px] font-bold uppercase tracking-[.08em] text-[#74827c]">{s.category||'Uncategorized'}</span></div><h3 className="mt-4 font-[Manrope] text-sm font-extrabold text-[#32494a]">{s.name}</h3><p className="mt-1.5 min-h-10 text-xs leading-5 text-[#7c8983]">{s.description||'No description has been added for this capability yet.'}</p><div className="mt-4 flex items-center justify-between border-t border-[#f0ede6] pt-3 text-[10px] text-[#82908a]"><span>{arr(data,'employeeSkills').filter(es=>String(es.skillId)===String(s.id)).length} team proficiencies</span><button onClick={()=>toast.message('Skill details are reflected in employee profiles.')} className="font-bold text-[#45816b] opacity-0 transition group-hover:opacity-100">View proficiency</button></div></article>)}
 {!filtered.length&&<div className="col-span-full"><Empty label={skills.length?'No skills match the current search and category.':'Add skills to create your organization’s capability framework.'} onAdd={()=>setDialog(true)}/></div>}</div></Panel>
 {dialog&&<RecordDialog kind="skill" close={()=>setDialog(false)} data={data} refresh={refresh}/>}</>;
}
function Certifications({data,refresh}:{data:AnyRow|null;refresh:()=>void}) {
 const certifications=arr(data,'certifications'); const employees=arr(data,'employees','people'); const [query,setQuery]=useState(''),[filter,setFilter]=useState('All statuses'),[dialog,setDialog]=useState(false);
 const getStatus=(c:AnyRow)=>{const days=(new Date(c.expiryDate||0).getTime()-Date.now())/86400000;return days<0?'Expired':days<61?'Expiring soon':'Current';};
 const list=certifications.filter(c=>`${c.name} ${c.provider||''} ${c.employeeName||''}`.toLowerCase().includes(query.toLowerCase())&&(filter==='All statuses'||getStatus(c)===filter));
 const nudge=(c:AnyRow)=>{const holder=employees.find(e=>String(e.id??e.employeeId)===String(c.employeeId));if(!holder?.email){toast.error('No email address is recorded for this credential holder.');return;}const subject=encodeURIComponent(`Certification renewal: ${c.name}`);const body=encodeURIComponent(`Hi ${holder.fullName||'there'},\n\nThis is a reminder that your ${c.name} certification expires on ${dateText(c.expiryDate)}. Please share your renewal plan with People Operations.\n`);window.location.href=`mailto:${holder.email}?subject=${subject}&body=${body}`;toast.success('Reminder draft opened in your email app');};
 return <><PageTitle eyebrow="Credential register" title="Certifications" subtitle="Keep professional credentials visible, current, and ahead of expiry." action={<Button onClick={()=>setDialog(true)}><Plus size={15}/>Add certification</Button>}/>
 <div className="mb-4 grid gap-3 sm:grid-cols-3"><MiniCount label="Current" value={certifications.filter(c=>getStatus(c)==='Current').length} accent="green"/><MiniCount label="Expiring soon" value={certifications.filter(c=>getStatus(c)==='Expiring soon').length} accent="amber"/><MiniCount label="Expired" value={certifications.filter(c=>getStatus(c)==='Expired').length} accent="rose"/></div>
 <Panel className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#eeeae2] p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-[380px] flex-1"><Search size={15} className="absolute left-3 top-3 text-[#8c9892]"/><input data-testid="input-search-certifications" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search credential, provider, or person…" className="w-full rounded-xl border border-[#e5e0d5] bg-[#fbfaf6] py-2.5 pl-9 pr-3 text-xs outline-none"/></div><select data-testid="filter-certification-status" value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-[#e5e0d5] bg-white px-3 py-2.5 text-xs"><option>All statuses</option>{['Current','Expiring soon','Expired'].map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="bg-[#faf9f5] text-[10px] uppercase tracking-[.12em] text-[#82908a]"><tr>{['Credential','Holder','Provider','Issued','Expires','Status',''].map(x=><th key={x} className="px-5 py-3 font-bold">{x}</th>)}</tr></thead><tbody className="divide-y divide-[#f0ede6]">{list.map((c,i)=>{const emp=employees.find(e=>String(e.id??e.employeeId)===String(c.employeeId));const status=getStatus(c);return <tr key={c.id??i} className="hover:bg-[#fbfaf6]"><td className="px-5 py-4"><div className="text-xs font-bold text-[#34494a]">{c.name}</div><div className="mt-1 text-[10px] text-[#89948f]">{c.category||'Professional credential'}</div></td><td className="px-5 py-4 text-xs text-[#596b66]">{c.employeeName||nameOf(emp||{})}</td><td className="px-5 py-4 text-xs text-[#687873]">{c.provider||'—'}</td><td className="px-5 py-4 text-xs text-[#687873]">{dateText(c.issueDate)}</td><td className="px-5 py-4 text-xs text-[#687873]">{dateText(c.expiryDate)}</td><td className="px-5 py-4"><StatusBadge value={status}/></td><td className="px-5 py-4"><button onClick={()=>nudge(c)} className="whitespace-nowrap text-[10px] font-bold text-[#47816b] hover:underline">Send reminder</button></td></tr>;})}{!list.length&&<TableEmpty colSpan={7} text={certifications.length?'No credentials match those filters.':'No certifications are recorded yet.'}/>}</tbody></table></div>
 </Panel>{dialog&&<RecordDialog kind="certification" close={()=>setDialog(false)} data={data} refresh={refresh}/>}</>;
}
function MiniCount({label,value,accent}:{label:string;value:number;accent:string}){const col:Record<string,string>={green:'text-[#438069] bg-[#e9f3ec]',amber:'text-[#b87c3e] bg-[#faf0e2]',rose:'text-[#ba6e61] bg-[#f8ece9]'};return <Panel className="flex items-center justify-between px-4 py-3"><div className="text-xs font-semibold text-[#73817c]">{label}</div><div className={`rounded-lg px-2.5 py-1.5 font-[Manrope] text-lg font-extrabold ${col[accent]}`}>{value}</div></Panel>}

function Training({data,refresh}:{data:AnyRow|null;refresh:()=>void}) {
 const courses=arr(data,'courses'), enrollments=arr(data,'enrollments'), employees=arr(data,'employees','people'), [query,setQuery]=useState(''),[category,setCategory]=useState('All courses'),[dialog,setDialog]=useState(false);
 const cats=Array.from(new Set(courses.map(c=>c.category).filter(Boolean)));
 const list=courses.filter(c=>`${c.name} ${c.description||''} ${c.category||''}`.toLowerCase().includes(query.toLowerCase())&&(category==='All courses'||c.category===category));
 const enroll=async(course:AnyRow)=>{if(!employees.length){toast.error('Add an employee before enrolling a learner.');return;}const choices=employees.map((e:any)=>`${e.id??e.employeeId} · ${nameOf(e)}`).join('\n');const person=window.prompt(`Enter an employee ID to enroll in ${course.name}:\n${choices}`,String(employees[0].id??employees[0].employeeId));if(!person)return;try{await enrollEmployee(person,course.id);toast.success('Enrollment created');await refresh();}catch(e){toast.error(e instanceof Error?e.message:'Could not enroll employee.')}};
 const advance=async(enrollment:AnyRow)=>{const progress=Math.min(100,(Number(enrollment.progress)||0)+25);try{await updateEnrollment(enrollment.id,progress);toast.success('Learning progress updated');await refresh();}catch(e){toast.error(e instanceof Error?e.message:'Could not update progress.')}};
 return <><PageTitle eyebrow="Learning operations" title="Training" subtitle="A practical catalogue of learning, with progress that stays connected to the people doing it." action={<Button onClick={()=>setDialog(true)}><Plus size={15}/>Add a course</Button>}/>
 <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-[390px] flex-1"><Search size={15} className="absolute left-3 top-3 text-[#8c9892]"/><input data-testid="input-search-courses" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a course…" className="w-full rounded-xl border border-[#e5e0d5] bg-white py-2.5 pl-9 text-xs outline-none"/></div><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-[#e5e0d5] bg-white px-3 py-2.5 text-xs"><option>All courses</option>{cats.map((c:any)=><option key={c}>{c}</option>)}</select></div>
 <div className="grid gap-4 lg:grid-cols-2">{list.map((c,i)=>{const enrolls=enrollments.filter(e=>String(e.courseId)===String(c.id));return <Panel key={c.id??i} className="overflow-hidden"><div className="flex items-start justify-between gap-4 border-b border-[#eeeae2] p-5"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#e9f1ec] text-[#4c886f]"><GraduationCap size={21}/></div><span className="rounded-full bg-[#f4f1e9] px-2.5 py-1 text-[9px] font-bold uppercase tracking-[.08em] text-[#74827c]">{c.category||'Learning'}</span></div><div className="p-5 pt-4"><Link href={`/training/${c.id}`} className="font-[Manrope] text-base font-extrabold text-[#2d4549] no-underline hover:text-[#39745f]">{c.name}</Link><p className="mt-2 min-h-10 text-xs leading-5 text-[#798781]">{c.description||'Course details have not been added yet.'}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-[10px] text-[#74817b]"><span>{c.instructor||'Instructor not set'}</span><span>{c.duration||'Duration not set'}</span><span>{enrolls.length} enrolled</span></div><div className="mt-4 flex items-center justify-between border-t border-[#f0ede6] pt-3"><div className="flex items-center gap-2 text-[10px] text-[#76847e]"><span className="h-2 w-2 rounded-full bg-[#70a889]"/>{c.requiredSkills?.length||0} required skills</div><div className="flex gap-2"><button onClick={()=>void enroll(c)} className="rounded-lg bg-[#276b58] px-3 py-2 text-[10px] font-bold text-white">Enroll learner</button>{enrolls[0]&&<button onClick={()=>void advance(enrolls[0])} className="rounded-lg border border-[#e1ddd2] px-3 py-2 text-[10px] font-bold text-[#4c6b61]">Update progress</button>}</div></div></div></Panel>})}
 {!list.length&&<div className="lg:col-span-2"><Panel><Empty label={courses.length?'No courses match your search or category.':'Add courses to build a learning catalogue for your teams.'} onAdd={()=>setDialog(true)}/></Panel></div>}</div>
 {dialog&&<RecordDialog kind="course" close={()=>setDialog(false)} data={data} refresh={refresh}/>}</>;
}

function SkillGaps({data,refresh}:{data:AnyRow|null;refresh:()=>void}) {
 const gaps=arr(data,'skillGaps','skillGapsData','gaps'), [priority,setPriority]=useState('All priorities');
 const list=gaps.filter(g=>!g.resolved&&(priority==='All priorities'||String(g.priority||'').toLowerCase()===priority.toLowerCase()));
 const resolve=async(g:AnyRow)=>{try{await resolveGap(g.id??g);toast.success('Skill gap marked resolved');await refresh();}catch(e){toast.error(e instanceof Error?e.message:'Could not resolve gap.')}};
 const enroll=async(g:AnyRow)=>{if(!g.recommendedCourse){toast.message('No course recommendation is linked to this gap yet.');return;}const course=arr(data,'courses').find(c=>String(c.id)===String(g.courseId??g.recommendedCourseId)||c.name===g.recommendedCourse);const courseId=course?.id??(typeof g.recommendedCourse==='object'?g.recommendedCourse.id:undefined);if(!courseId){toast.error('The recommended course could not be found.');return;}try{await enrollEmployee(g.employeeId,courseId);toast.success('Recommended course assigned');await refresh();}catch(e){toast.error(e instanceof Error?e.message:'Could not enroll learner.')}};
 return <><PageTitle eyebrow="Workforce planning" title="Skill gaps" subtitle="Turn priority capability needs into a focused next step for each person." action={<select data-testid="filter-gap-priority" value={priority} onChange={e=>setPriority(e.target.value)} className="rounded-xl border border-[#e5e0d5] bg-white px-3 py-2.5 text-xs"><option>All priorities</option>{['High','Medium','Low'].map(x=><option key={x}>{x}</option>)}</select>}/>
 <div className="mb-5 grid gap-3 sm:grid-cols-3"><MiniCount label="Open priorities" value={gaps.filter(g=>!g.resolved&&String(g.priority).toLowerCase()==='high').length} accent="rose"/><MiniCount label="In development" value={arr(data,'enrollments').filter(e=>e.status==='In progress'||e.status==='in_progress').length} accent="blue"/><MiniCount label="Resolved" value={gaps.filter(g=>g.resolved).length} accent="green"/></div>
 <Panel className="overflow-hidden"><div className="border-b border-[#eeeae2] px-5 py-4"><h2 className="font-[Manrope] text-sm font-extrabold text-[#2c4548]">Prioritized development opportunities</h2><p className="mt-1 text-[11px] text-[#7c8983]">Match a capability gap with learning that moves it forward.</p></div>
  <div className="divide-y divide-[#f0ede6]">{list.map((g,i)=>{const delta=Math.max(0,Math.round((levelPercent(g.requiredLevel)-levelPercent(g.currentLevel))/20));const course=typeof g.recommendedCourse==='string'?g.recommendedCourse:g.recommendedCourse?.name;const progress=levelPercent(g.currentLevel);return <article key={g.id??i} className="grid gap-4 p-5 md:grid-cols-[1fr_1fr_auto] md:items-center"><div className="flex items-start gap-3"><span className={`mt-0.5 grid h-9 w-9 shrink-0 place-items-center rounded-xl ${String(g.priority).toLowerCase()==='high'||String(g.priority).toLowerCase()==='critical'?'bg-[#faece7] text-[#b86e5e]':'bg-[#f9f1e4] text-[#b88443]'}`}><Target size={17}/></span><div><div className="text-xs font-bold text-[#324a4a]">{g.skillName||g.skill?.name||g.name||'Capability gap'}</div><div className="mt-1 text-[10px] text-[#81908a]">{g.employeeName||g.fullName||'Team member'}{g.department?` · ${g.department}`:''}</div></div></div><div><div className="mb-2 flex items-center justify-between text-[10px]"><span className="text-[#81908a]">Current → required</span><span className="font-mono font-medium text-[#50635e]">{g.currentLevel??'—'} / {g.requiredLevel??'—'}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#ece9e0]"><div className="h-full rounded-full bg-[#6ca58a]" style={{width:`${progress}%`}}/></div><div className="mt-1.5 text-[9px] text-[#9aa39d]">{delta?`${delta} level${delta===1?'':'s'} to close`:'Level requirement met'}</div></div><div className="flex items-center gap-2"><span className="rounded-full bg-[#f8efe6] px-2.5 py-1 text-[9px] font-bold uppercase text-[#aa7744]">{g.priority||'Normal'}</span><button onClick={()=>void enroll(g)} disabled={!g.recommendedCourse} className="rounded-lg bg-[#276b58] px-3 py-2 text-[10px] font-bold text-white disabled:cursor-not-allowed disabled:opacity-45">Assign course</button><button title="Mark resolved" aria-label="Resolve skill gap" onClick={()=>void resolve(g)} className="rounded-lg border border-[#e3dfd5] p-2 text-[#6f8279] hover:bg-[#edf4ef]"><Check size={14}/></button></div><div className="md:col-start-2 -mt-2 text-[10px] text-[#7e8a84]">Recommended: <span className="font-semibold text-[#4b6a60]">{course||'No course recommendation'}</span></div></article>})}
 {!list.length&&<Empty label={gaps.length?'There are no open gaps at this priority.':'Skill gap records will appear once capability requirements are mapped.'}/>}</div></Panel></>;
}

function Analytics({data}:{data:AnyRow|null}) {
 const people=arr(data,'employees','people'), enroll=arr(data,'enrollments'), gaps=arr(data,'skillGaps','skillGapsData','gaps'), depts=Array.from(new Set(people.map(e=>e.department).filter(Boolean)));
 const groups=depts.map((d:any)=>{const members=people.filter(e=>e.department===d);const deptGaps=gaps.filter(g=>members.some(m=>String(m.id??m.employeeId)===String(g.employeeId))&&!g.resolved);const learning=enroll.filter(e=>members.some(m=>String(m.id??m.employeeId)===String(e.employeeId)));return {name:d,total:members.length,gaps:deptGaps.length,learning:learning.length,complete:learning.filter(e=>Number(e.progress)>=100||e.status==='Completed').length};});
 const max=Math.max(1,...groups.map(g=>g.total));
 return <><PageTitle eyebrow="People intelligence" title="Analytics" subtitle="Compare capability investment and learning momentum across departments." action={<Button secondary onClick={()=>window.print()}><Download size={14}/>Export view</Button>}/>
 <div className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><Panel className="p-5 md:p-6"><div className="flex items-start justify-between"><div><h2 className="font-[Manrope] text-base font-extrabold text-[#2c4448]">Department comparison</h2><p className="mt-1 text-xs text-[#7b8782]">Headcount against open skill gaps</p></div><span className="mono text-[9px] text-[#99a39d]">LIVE DATA</span></div>
 {groups.length?<div className="mt-7 space-y-5">{groups.map(g=><div key={g.name}><div className="mb-2 flex items-center justify-between"><div className="text-xs font-bold text-[#405553]">{g.name}</div><div className="text-[10px] text-[#82908a]">{g.total} people · {g.gaps} open gaps</div></div><div className="relative h-3 overflow-hidden rounded-full bg-[#ece9e0]"><div className="absolute inset-y-0 left-0 rounded-full bg-[#6da78b]" style={{width:`${g.total/max*100}%`}}/><div className="absolute inset-y-0 left-0 rounded-full bg-[#dc9a57]/90" style={{width:`${Math.min(g.total/max*100,g.gaps/max*100*2)}%`}}/></div></div>)}</div>:<Empty label="Department comparisons will appear as your employee records are organized."/>}
 <div className="mt-6 flex gap-4 border-t border-[#eeeae2] pt-4 text-[10px] text-[#75827d]"><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-[#6da78b]"/>People</span><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-[#dc9a57]"/>Open gaps</span></div></Panel>
 <Panel className="p-5 md:p-6"><h2 className="font-[Manrope] text-base font-extrabold text-[#2c4448]">Learning outcomes</h2><p className="mt-1 text-xs text-[#7b8782]">Enrollments across your teams</p><div className="mt-7 grid grid-cols-2 gap-3"><Outcome value={enroll.length} label="Total enrollments" tone="green"/><Outcome value={enroll.filter(e=>e.status==='In progress'||e.status==='in_progress').length} label="In progress" tone="blue"/><Outcome value={enroll.filter(e=>Number(e.progress)>=100||e.status==='Completed').length} label="Completed" tone="amber"/><Outcome value={gaps.filter(g=>g.resolved).length} label="Gaps resolved" tone="rose"/></div><div className="mt-5 rounded-xl bg-[#f7f5ef] p-4"><div className="flex items-center gap-2 text-xs font-bold text-[#4a615b]"><ArrowUpRight size={15} className="text-[#559176]"/>Completion rate</div><div className="mt-2 flex items-end justify-between"><span className="font-[Manrope] text-3xl font-extrabold text-[#2e494b]">{enroll.length?Math.round(enroll.filter(e=>Number(e.progress)>=100||e.status==='Completed').length/enroll.length*100):0}%</span><span className="text-[10px] text-[#85928c]">of tracked enrollments</span></div></div></Panel></div>
 <Panel className="mt-4 overflow-hidden"><div className="border-b border-[#eeeae2] px-5 py-4"><h2 className="font-[Manrope] text-sm font-extrabold text-[#2c4448]">Department breakdown</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left"><thead className="bg-[#faf9f5] text-[10px] uppercase tracking-[.1em] text-[#82908a]"><tr>{['Department','People','Active enrollments','Completed','Open gaps'].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-[#f0ede6]">{groups.map(g=><tr key={g.name}><td className="px-5 py-3 text-xs font-bold text-[#405553]">{g.name}</td><td className="px-5 py-3 text-xs">{g.total}</td><td className="px-5 py-3 text-xs">{g.learning}</td><td className="px-5 py-3 text-xs">{g.complete}</td><td className="px-5 py-3 text-xs">{g.gaps}</td></tr>)}{!groups.length&&<TableEmpty colSpan={5} text="Department data will populate from employee profiles."/>}</tbody></table></div></Panel></>;
}
function Outcome({value,label,tone}:{value:number;label:string;tone:string}){const colors:Record<string,string>={green:'text-[#438069]',blue:'text-[#557b8b]',amber:'text-[#b88443]',rose:'text-[#ba6e61]'};return <div className="rounded-xl bg-[#f7f5ef] p-3.5"><div className={`font-[Manrope] text-2xl font-extrabold ${colors[tone]}`}>{value}</div><div className="mt-1 text-[10px] text-[#7b8983]">{label}</div></div>}

function EmployeeProfile({data,refresh}:{data:AnyRow|null;refresh:()=>void}) {
 const params=useParams<{id:string}>(); const people=arr(data,'employees','people');const employee=people.find(e=>String(e.id??e.employeeId)===String(params.id));
 const proficiencies=arr(data,'employeeSkills').filter(x=>String(x.employeeId)===String(params.id));const skills=arr(data,'skills');const certs=arr(data,'certifications').filter(x=>String(x.employeeId)===String(params.id));const enrollments=arr(data,'enrollments').filter(x=>String(x.employeeId)===String(params.id));
 const changeSkill=async(id:any,level:string)=>{const choices=['','Beginner','Basic','Intermediate','Advanced','Expert'];const normalized=choices[Number(level)]||level;const score:Record<string,number>={Beginner:20,Basic:35,Intermediate:60,Advanced:80,Expert:100};try{await updateEmployeeSkill(params.id||'',String(id),normalized as SkillLevel,score[normalized]||0);toast.success('Proficiency updated');await refresh();}catch(e){toast.error(e instanceof Error?e.message:'Could not update proficiency.')}};
 if(!employee)return <><Link href="/employees" className="text-xs font-bold text-[#41806a] no-underline">← Back to people</Link><div className="mt-5"><Empty label="This employee profile could not be found in the current workspace."/></div></>;
 return <><Link href="/employees" className="mb-5 inline-flex items-center gap-2 text-xs font-bold text-[#45816b] no-underline">← All employees</Link><PageTitle eyebrow="Employee profile" title={nameOf(employee)} subtitle={`${employee.jobRole||'Role not set'} · ${employee.department||'Department not set'}` } action={<Button secondary onClick={()=>toast.message('Edit employee details from the directory.')}>Edit profile</Button>}/>
 <div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><Panel className="p-5"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#e9f1ec] text-lg font-bold text-[#447d67]">{initials(nameOf(employee))}</div><div><h2 className="font-[Manrope] text-lg font-extrabold text-[#30494a]">{nameOf(employee)}</h2><div className="mt-1 text-xs text-[#7c8983]">{employee.employeeId||employee.id} · <StatusBadge value={employee.status||'Active'}/></div></div></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-[#eeeae2] pt-4">{[['Email',employee.email],['Phone',employee.phone],['Manager',employee.manager],['Location',employee.location],['Joined',dateText(employee.joiningDate)],['Department',employee.department]].map(([k,v])=><div key={k}><div className="text-[9px] font-bold uppercase tracking-[.12em] text-[#99a39d]">{k}</div><div className="mt-1 break-words text-xs text-[#52635f]">{v||'Not provided'}</div></div>)}</div></Panel>
 <Panel className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-[Manrope] text-sm font-extrabold text-[#2c4448]">Development plan</h2><p className="mt-1 text-[11px] text-[#7b8782]">Skills to grow, courses underway, and credentials</p></div><span className="rounded-lg bg-[#edf4ef] px-2 py-1 text-[9px] font-bold text-[#47816b]">{proficiencies.length} tracked skills</span></div><div className="mt-4 space-y-2">{proficiencies.map((p,i)=>{const skill=skills.find(s=>String(s.id)===String(p.skillId));return <div key={p.id??i} className="flex items-center gap-3 rounded-xl bg-[#f8f7f1] p-3"><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold text-[#435754]">{skill?.name||p.skillName||'Skill'}</div><div className="mt-1 text-[10px] text-[#87928d]">{skill?.category||'Capability'} · current level {p.level??p.proficiency??'—'}</div></div><select aria-label={`Update ${skill?.name||'skill'} proficiency`} defaultValue={p.level??p.proficiency??''} onChange={e=>void changeSkill(p.skillId,e.target.value)} className="rounded-lg border border-[#e2ded4] bg-white px-2 py-1.5 text-[10px]"><option value="">Level</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>Level {n}</option>)}</select></div>})}{!proficiencies.length&&<p className="py-6 text-center text-xs text-[#89958f]">No skills have been assessed for this employee yet.</p>}</div></Panel></div>
 <div className="mt-4 grid gap-4 lg:grid-cols-2"><Panel className="p-5"><h2 className="font-[Manrope] text-sm font-extrabold text-[#2c4448]">Credentials</h2>{certs.map((c,i)=><div key={c.id??i} className="mt-3 flex items-center justify-between border-b border-[#f0ede6] pb-3 last:border-0"><div><div className="text-xs font-bold text-[#465a56]">{c.name}</div><div className="mt-1 text-[10px] text-[#89948f]">{c.provider||'Provider not set'}</div></div><StatusBadge value={dateText(c.expiryDate)}/></div>)}{!certs.length&&<div className="mt-3 text-xs text-[#89958f]">No certifications recorded.</div>}</Panel>
 <Panel className="p-5"><h2 className="font-[Manrope] text-sm font-extrabold text-[#2c4448]">Learning activity</h2>{enrollments.map((en,i)=>{const course=arr(data,'courses').find(c=>String(c.id)===String(en.courseId));return <div key={en.id??i} className="mt-3 border-b border-[#f0ede6] pb-3 last:border-0"><div className="flex justify-between text-xs"><span className="font-bold text-[#465a56]">{course?.name||en.courseName||'Course enrollment'}</span><span className="mono text-[10px] text-[#71827a]">{pct(en.progress)}</span></div><div className="mt-2 h-1.5 rounded-full bg-[#ece9e0]"><div className="h-1.5 rounded-full bg-[#68a386]" style={{width:pct(en.progress)}}/></div></div>})}{!enrollments.length&&<div className="mt-3 text-xs text-[#89958f]">No active course enrollments.</div>}</Panel></div></>;
}

function CourseDetail({data,refresh}:{data:AnyRow|null;refresh:()=>void}) {
 const {id}=useParams<{id:string}>();const course=arr(data,'courses').find(c=>String(c.id)===String(id));const enrollments=arr(data,'enrollments').filter(e=>String(e.courseId)===String(id));
 const update=async(en:AnyRow)=>{const progress=window.prompt('Set course progress (0–100):',String(en.progress??0));if(progress===null)return;const amount=Math.min(100,Math.max(0,Number(progress)||0));try{await updateEnrollment(en.id,amount);toast.success('Progress saved');await refresh();}catch(e){toast.error(e instanceof Error?e.message:'Could not save progress.')}};
 if(!course)return <><Link href="/training" className="text-xs font-bold text-[#45816b] no-underline">← Training catalogue</Link><div className="mt-4"><Empty label="This course is not available in the current workspace."/></div></>;
 return <><Link href="/training" className="mb-5 inline-flex text-xs font-bold text-[#45816b] no-underline">← Training catalogue</Link><PageTitle eyebrow={course.category||'Learning course'} title={course.name} subtitle={course.description||'Course information and enrollment progress.'} action={<Button secondary onClick={()=>toast.message('Edit course details from the training catalogue.')}>Edit course</Button>}/>
 <div className="grid gap-4 lg:grid-cols-[.75fr_1.25fr]"><Panel className="p-5"><h2 className="font-[Manrope] text-sm font-extrabold text-[#2c4448]">Course details</h2><div className="mt-4 space-y-3">{[['Instructor',course.instructor],['Duration',course.duration],['Category',course.category]].map(([l,v])=><div key={l}><div className="text-[9px] font-bold uppercase tracking-[.12em] text-[#99a39d]">{l}</div><div className="mt-1 text-xs text-[#52635f]">{v||'Not provided'}</div></div>)}</div><div className="mt-5 border-t border-[#eeeae2] pt-4"><div className="text-[9px] font-bold uppercase tracking-[.12em] text-[#99a39d]">Required skills</div><div className="mt-2 flex flex-wrap gap-2">{(course.requiredSkills||[]).map((s:any,i:number)=><span key={i} className="rounded-full bg-[#edf4ef] px-2.5 py-1.5 text-[10px] font-semibold text-[#477b67]">{typeof s==='string'?s:s.name}</span>)}{!course.requiredSkills?.length&&<span className="text-xs text-[#89958f]">No prerequisite skills listed.</span>}</div></div></Panel>
 <Panel className="overflow-hidden"><div className="border-b border-[#eeeae2] p-5"><h2 className="font-[Manrope] text-sm font-extrabold text-[#2c4448]">Learner progress</h2><p className="mt-1 text-[11px] text-[#7b8782]">{enrollments.length} enrolled in this course</p></div>{enrollments.map((en,i)=>{const person=arr(data,'employees','people').find(p=>String(p.id??p.employeeId)===String(en.employeeId));return <div key={en.id??i} className="flex flex-wrap items-center gap-3 border-b border-[#f0ede6] px-5 py-4 last:border-0"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#eaf1ec] text-[10px] font-bold text-[#3e7664]">{initials(nameOf(person||{}))}</div><div className="min-w-[120px] flex-1"><div className="text-xs font-bold text-[#405653]">{nameOf(person||{})}</div><div className="mt-1 text-[10px] text-[#89948f]">Due {dateText(en.dueDate)}</div></div><div className="w-[120px]"><div className="mb-1 text-right mono text-[9px] text-[#72817b]">{pct(en.progress)}</div><div className="h-1.5 rounded-full bg-[#ece9e0]"><div className="h-1.5 rounded-full bg-[#6ca58a]" style={{width:pct(en.progress)}}/></div></div><StatusBadge value={en.status||'Not started'}/><button onClick={()=>void update(en)} className="rounded-lg border border-[#e2ded4] px-3 py-2 text-[10px] font-bold text-[#4b7062]">Update</button></div>})}{!enrollments.length&&<Empty label="No one is enrolled yet. Find this course in the catalogue to enroll an employee."/ >}</Panel></div></>;
}

function SettingsPage({data,refresh}:{data:AnyRow|null;refresh:()=>void}) {
 const s={...(data?.settings||{}),name:data?.settings?.displayName};const [dialog,setDialog]=useState(false);const [loc,setLoc]=useLocation();const [prefs,setPrefs]=useState({certificationExpiry:s.notifications?.certificationExpiry??true,trainingReminders:s.notifications?.trainingReminders??true,skillGapAlerts:s.notifications?.skillGapAlerts??true,weeklySummary:s.notifications?.weeklySummary??false});
 const toggle=(key:keyof typeof prefs)=>setPrefs(p=>({...p,[key]:!p[key]}));
 const savePrefs=async()=>{try{await saveSettings({...s,notifications:prefs} as AppSettings);toast.success('Preferences saved');await refresh();}catch(e){toast.error(e instanceof Error?e.message:'Could not save preferences.')}};
 return <><PageTitle eyebrow="Workspace administration" title="Settings" subtitle="Manage your organization profile and the updates your team receives." action={getDataMode()==='supabase'?<button onClick={async()=>{try{await signOut();toast.success('Signed out');setLoc('/auth');}catch(e){toast.error(e instanceof Error?e.message:'Could not sign out.');}}} className="rounded-xl border border-[#e3dfd5] bg-white px-4 py-2.5 text-xs font-bold text-[#52635f]">Sign out</button>:undefined}/>
 <div className="grid gap-4 xl:grid-cols-[.85fr_1.15fr]"><Panel className="p-5 md:p-6"><div className="flex items-start justify-between"><div><h2 className="font-[Manrope] text-base font-extrabold text-[#2c4448]">Organization</h2><p className="mt-1 text-xs text-[#7b8782]">Workspace identity and contact details</p></div><Button secondary onClick={()=>setDialog(true)}>Edit details</Button></div><div className="mt-5 rounded-xl bg-[#f7f5ef] p-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#dcebe1] text-[#34715b]"><BriefcaseBusiness size={18}/></div><div><div className="text-sm font-bold text-[#405653]">{s.organizationName||'Organization name'}</div><div className="mt-1 text-[10px] text-[#82908a]">SkillTrack workspace</div></div></div><div className="mt-4 grid grid-cols-2 gap-4 border-t border-[#e8e4db] pt-4"><div><div className="text-[9px] font-bold uppercase tracking-[.12em] text-[#99a39d]">Workspace owner</div><div className="mt-1 text-xs text-[#52635f]">{s.name||'Not provided'}</div></div><div><div className="text-[9px] font-bold uppercase tracking-[.12em] text-[#99a39d]">Contact email</div><div className="mt-1 break-all text-xs text-[#52635f]">{s.email||'Not provided'}</div></div></div></div></Panel>
 <Panel className="p-5 md:p-6"><h2 className="font-[Manrope] text-base font-extrabold text-[#2c4448]">Preferences</h2><p className="mt-1 text-xs text-[#7b8782]">Control the signals that keep your team informed.</p><div className="mt-4 divide-y divide-[#f0ede6]">{([[ 'certificationExpiry','Certification expiry reminders','Get ahead of credentials that need renewal'],['trainingReminders','Training reminders','Nudge learners when due dates approach'],['skillGapAlerts','Skill gap alerts','Keep priority development needs visible'],['weeklySummary','Weekly learning digest','A Monday overview of course progress']] as [keyof typeof prefs,string,string][]).map(([key,title,detail])=><label key={key} className="flex cursor-pointer items-center gap-4 py-4"><span className="flex-1"><span className="block text-xs font-bold text-[#465a56]">{title}</span><span className="mt-1 block text-[10px] text-[#84918b]">{detail}</span></span><input data-testid={`toggle-${key}`} type="checkbox" checked={prefs[key]} onChange={()=>toggle(key)} className="h-4 w-4 accent-[#35755e]"/></label>)}</div><div className="mt-4 flex justify-end"><Button onClick={()=>void savePrefs()}>Save preferences</Button></div></Panel></div>
 {dialog&&<RecordDialog kind="settings" initial={s} close={()=>setDialog(false)} data={data} refresh={refresh}/>}</>;
}

function AuthPage() {
 const [loc,setLoc]=useLocation();const signup=loc==='/auth/signup';const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[organization,setOrganization]=useState(''),[busy,setBusy]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{
   if(!isSupabaseConfigured){toast.error('Authentication is not configured for this workspace yet. Use the demo workspace.');return;}
   if(signup) await signUpWithPassword(email,password,{displayName:name,organizationName:organization});
   else await signInWithPassword(email,password);
   toast.success(signup?'Account created':'Signed in');setLoc('/dashboard');
 }catch(e){toast.error(e instanceof Error?e.message:'Authentication failed.')}finally{setBusy(false);}};
 return <div className="grid min-h-[calc(100dvh-140px)] place-items-center"><div className="w-full max-w-[440px] overflow-hidden rounded-3xl border border-[#e6e1d7] bg-white shadow-[0_18px_65px_rgba(38,58,56,.1)]"><div className="bg-[#19333b] px-8 py-8 text-white"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#74bca0] text-[#19333b]"><BriefcaseBusiness size={18}/></div><span className="font-[Manrope] font-extrabold tracking-[-.04em]">skilltrack.</span></div><div className="mt-8 text-[10px] font-bold uppercase tracking-[.18em] text-[#8dc9ad]">Your people, in progress</div><h1 className="mt-2 font-[Manrope] text-2xl font-extrabold">{signup?'Create your workspace account':'Welcome back'}</h1><p className="mt-2 text-xs leading-5 text-[#c0ceca]">A clear view of the skills moving your organization forward.</p></div><form onSubmit={submit} className="space-y-4 p-8">{signup&&<><label className="block text-[11px] font-bold text-[#52635f]">Full name<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[#e3dfd5] bg-[#fbfaf6] px-3 py-3 text-xs font-normal outline-none focus:border-[#79a995]"/></label><label className="block text-[11px] font-bold text-[#52635f]">Organization<input required value={organization} onChange={e=>setOrganization(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[#e3dfd5] bg-[#fbfaf6] px-3 py-3 text-xs font-normal outline-none focus:border-[#79a995]"/></label></>}<label className="block text-[11px] font-bold text-[#52635f]">Work email<input data-testid="input-auth-email" required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[#e3dfd5] bg-[#fbfaf6] px-3 py-3 text-xs font-normal outline-none focus:border-[#79a995]"/></label><label className="block text-[11px] font-bold text-[#52635f]">Password<input data-testid="input-auth-password" required type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[#e3dfd5] bg-[#fbfaf6] px-3 py-3 text-xs font-normal outline-none focus:border-[#79a995]"/></label><button disabled={busy} className="mt-2 w-full rounded-xl bg-[#276b58] py-3 text-xs font-bold text-white disabled:opacity-60">{busy?'Please wait…':signup?'Create account':'Sign in'}</button><button type="button" onClick={()=>{useDemoMode();toast.success('Demo workspace activated');setLoc('/dashboard');}} className="w-full rounded-xl border border-[#dce4dc] bg-[#f2f7f2] py-3 text-xs font-bold text-[#34715b]">Continue with demo workspace</button><div className="pt-1 text-center text-xs text-[#7f8b85]">{signup?'Already have an account?':'New to SkillTrack?'} <Link href={signup?'/auth':'/auth/signup'} className="font-bold text-[#367962] no-underline">{signup?'Sign in':'Create an account'}</Link></div></form></div></div>;
}

export function WorkspacePages() {
 const {data,error,loading,refresh}=useWorkspace();const [path]=useLocation();
 if(path==='/auth'||path==='/auth/signup')return <AuthPage/>;
 if(loading)return <LoadingPage/>;
 if(error)return <ErrorPanel error={error} retry={refresh}/>;
 let page;
 if(path==='/dashboard'||path==='/')page=<Dashboard data={data} loading={loading} error={error} refresh={refresh}/>;
 else if(path==='/employees')page=<Employees data={data} refresh={refresh}/>;
 else if(path.startsWith('/employees/'))page=<EmployeeProfile data={data} refresh={refresh}/>;
 else if(path==='/skills')page=<Skills data={data} refresh={refresh}/>;
 else if(path==='/certifications')page=<Certifications data={data} refresh={refresh}/>;
 else if(path==='/training')page=<Training data={data} refresh={refresh}/>;
 else if(path.startsWith('/training/'))page=<CourseDetail data={data} refresh={refresh}/>;
 else if(path==='/skill-gaps')page=<SkillGaps data={data} refresh={refresh}/>;
 else if(path==='/analytics')page=<Analytics data={data}/>;
 else if(path==='/settings')page=<SettingsPage data={data} refresh={refresh}/>;
 else page=<Dashboard data={data} loading={loading} error={error} refresh={refresh}/>;
 return <>{page}</>;
}
